# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
jobs:
  Example-Actions-Job:
    name: explore github actions
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{github.event_name}} event."
      - run: echo "This job is now wunning on a ${{ runner.os }} server hosted by github."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}. "
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - run: echo "the ${{ github.repository }} repository has been cloned to the runner. "
      - run: echo "Your repository has been copied to the path ${{ github.workspace }}  on the runner. "
      - run: echo "The workflow is now ready to test your code on the runner. "
      
      - name: conditional step when even name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"
        
      - name: List files in the repostory
        run: |
          ls ${{ github.wordspace }}
          
      - name: setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
          
      - name: Display dotnet version
        run: dotnet --version
        
      - name: list files in tool cache
        run: |
          ls ${{ runner.tool_cache }}
          
      - run: echo "This job's status is ${{ job.status }}. "
      
  
